config/routes.rb
Rails.application.routes.draw do
  resources :registered_applications
  devise_for :users
  
  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end
  
  root 'welcome#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :registered_application
end

app/models/registered_application.rb
class RegisteredApplication < ActiveRecord::Base
  belongs_to :user
  has_many :events
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :registered_applications
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
    skip_before_action :verify_authenticity_token
    before_filter :set_access_control_headers
    
    def set_access_control_headers
        headers['Access-Control-Allow-Origin'] = '*'
        headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
        headers['Access-Control-Allow-Headers'] = 'Content-Type'
    end
    
    def create
        @registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])
        if @registered_application == nil
            render json: "Unregistered application", status: :unprocessable_entity    
        end
        @event = @registered_application.events.new(event_params)
        
        if @event.save
            render json: @event, status: :created
        else
            render json: {errors: @event.errors}, status: :unprocessable_entity
        end
    end
    
    def preflight
        head 200
    end

    private
    def event_params
        params.require(:event).permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
    
    def index
        @registered_applications = RegisteredApplication.all
    end
    
    def show
        @registered_application = RegisteredApplication.find(params[:id])
        @events = @registered_application.events.group_by(&:name)
    end
    
    def new
        @registered_application = RegisteredApplication.new
    end
    
    def create
        @registered_application = RegisteredApplication.new(registered_application_params)
        
        if @registered_application.save
            redirect_to @registered_application, notice: "Application was saved successfully."
        else
            flash.now[:alert] = "Error creating application. Please try again."
            render :new
        end
    end
    
    def edit
        @registered_application = RegisteredApplication.find(params[:id])
    end
    
    def update
        @registered_application = RegisteredApplication.find(params[:id])
        
        @registered_application.assign_attributes(registered_application_params)
        
        if @registered_application.save
            flash[:notice] = "Application was updated."
            redirect_to @registered_application
        else
            flash.now[:alert] = "Error saving application. Please try again."
            render :edit
        end
    end
    
    def destroy
        @registered_application = RegisteredApplication.find(params[:id])
        
        if @registered_application.destroy
            flash[:notice] = "\"#{@registered_application.name}\" was deleted successfully."
            redirect_to action: :index
        else
            flash.now[:alert] = "There was an error deleting the application."
            render :show
        end
    end
    
    private
    def registered_application_params
        params.require(:registered_application).permit(:name, :url)
    end
    
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmetrics</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<ul class="nav nav-tabs">
  <li><%= link_to "Blocmetrics", root_path %></li>
  <li><%= link_to "Applications", registered_applications_path %></li>
</ul>

<% if user_signed_in? %>
  Signed in as: <strong><%= current_user.email %></strong> |
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
  <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissable" role="alert">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:notice] %>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-warning alert-dismissable" role="alert">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:alert] %>
  </div>
<% end %>

<%= yield %>

</body>
</html>

app/views/registered_applications/edit.html.erb
<h1>Edit Application</h1>

<div class="row">
    <div class="col-md-8">
        <%= form_for @registered_application do |f| %>
            <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: 'form-control', placeholder: "Enter application name" %>
            </div>
            <div class="form-group">
                <%= f.label :url %>
                <%= f.text_field :url, class: 'form-control', placeholder: "Enter application url" %>
            </div>
            <%= f.submit "Save", class: 'btn btn-success' %>
        <% end %>
    </div>
</div>

app/views/registered_applications/index.html.erb
<h1>Applications</h1>

<div class="row">
    <div class="col-md-8">
        <%= link_to "Add Application", new_registered_application_path, class: 'btn btn-success' %>
    </div>
    <div class="col-md-8">
        <% @registered_applications.each do |application| %>
            <div class="media">
                <div class="media-body">
                    <h4 class="media-heading">
                        <%= link_to application.name, application %>
                    </h4>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/registered_applications/new.html.erb
<h1>Add Application</h1>
 
 <div class="row">
     <div class="col-md-8">
         <%= form_for @registered_application do |f| %>
           <div class="form-group">
             <%= f.label :name %>
             <%= f.text_field :name, class: 'form-control', placeholder: "Enter application name" %>
           </div>
           <div class="form-group">
             <%= f.label :url %>
             <%= f.text_field :url, class: 'form-control', placeholder: "Enter application url" %>
           </div>
           <%= f.submit "Save", class: 'btn btn-success' %>
         <% end %>
     </div>
 </div>

app/views/registered_applications/show.html.erb
<h1><%= @registered_application.name %></h1>

<div class="row">
    <div class="col-md-8">
        <a href="<%= @registered_application.url %>">Link to App</a>
        <h2>Events</h2>
    </div>
    <div class="col-md-8">
        <div class="media">
            <div class="media-body">
                <h5 class="media-heading">
                    <%= pie_chart @registered_application.events.group(:name).count %>
                    <%= line_chart @registered_application.events.group_by_day(:created_at).count %>
                </h5>
            </div>
        </div>
    </div>
</div>

<%= link_to "Edit Application", edit_registered_application_path, class: 'btn btn-success' %>
<%= link_to "Delete Application", @registered_application, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this application?' } %>

app/views/welcome/index.html.erb
<h1>Welcome to Blocmetrics</h1>